// @flow

export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START'
export const LOAD_ARTICLES_FINISHED = 'LOAD_ARTICLES_FINISHED'
export const LOAD_ARTICLES_FAILED = 'LOAD_ARTICLES_FAILED'

export const LOAD_AUTHORS_FOR_ARTICLE_START = 'LOAD_AUTHORS_FOR_ARTICLE_START'
export const LOAD_AUTHORS_FOR_ARTICLE_FINISHED = 'LOAD_AUTHORS_FOR_ARTICLE_FINISHED'
export const LOAD_AUTHORS_FOR_ARTICLE_FAILED = 'LOAD_AUTHORS_FOR_ARTICLE_FAILED'

export const LOAD_ARTICLE_DETAILS_START = 'LOAD_ARTICLE_DETAILS_START'
export const LOAD_ARTICLE_DETAILS_FINISHED = 'LOAD_ARTICLE_DETAILS_FINISHED'
export const LOAD_ARTICLE_DETAILS_FAILED = 'LOAD_ARTICLE_DETAILS_FAILED'

export const SELECT_ARTICLE = 'SELECT_ARTICLE'